//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Malco.Integracion.Clientes.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetalleFacturas
    {
        public int NConsecutivoNacional { get; set; }
        public int NNroFactura { get; set; }
        public int NConsDo { get; set; }
        public short NCodigoGasto { get; set; }
        public string CTipo { get; set; }
        public int NValor { get; set; }
        public int nVlrSaldoNotaCredito { get; set; }
        public string CNroDocReferencia { get; set; }
        public Nullable<decimal> NIva { get; set; }
        public Nullable<long> NIdProveedor { get; set; }
        public Nullable<short> NDigitoChequeo { get; set; }
        public string cCuenta { get; set; }
        public string cDescripcion { get; set; }
        public Nullable<short> NGrupo { get; set; }
        public Nullable<decimal> NReteFuente { get; set; }
        public Nullable<decimal> NReteIva { get; set; }
        public Nullable<decimal> NReteIca { get; set; }
        public string CTipoIngreso { get; set; }
        public string CContabiliza { get; set; }
        public string CCentro { get; set; }
        public string CPlata { get; set; }
        public string CDevolverA { get; set; }
        public Nullable<int> NConsecutivo { get; set; }
        public string CNroDocumento { get; set; }
        public Nullable<short> NNaturaleza { get; set; }
        public int nConsDetalle { get; set; }
    
        public virtual tbEncabezadoFacturas tbEncabezadoFacturas { get; set; }
    }
}
